name: CI
on: [push, pull_request]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: cmake -B build
        - run: cmake --build build
        - run: ctest --test-dir build --output-on-failure
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install gcovr
            - run: cmake -B build -DQSIM_COVERAGE=ON
            - run: cmake --build build
            - run: ctest --test-dir build
            - run: gcovr --root . --filter src/ --filter include/ --cobertura coverage.xml build
            - uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}

