name: CI
on: [push, pull_request]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: cmake --preset debug
        - run: cmake --build --preset debug
        - run: ctest --preset debug
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install gcovr
            - run: cmake --preset coverage
            - run: cmake --build --preset coverage
            - run: ctest --preset coverage
            - run: gcovr --root . --filter src/ --filter include/ --cobertura coverage.xml build/coverage
            - uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
    build-benchmark:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: cmake --preset benchmark
        - run: cmake --build --preset benchmark --target qsim_bench
        - run: ./build/benchmark/qsim_bench --benchmark_list_tests=true

